### ISSUE TITLE
我的主页建议增加所有项目的汇总信息

### ISSUE THREAD

**Issue by xuzhiqing888** [alexqin2018/cloud#10]
1.权限范围内所有项目的缺陷总数，缺陷密度（千行代码缺陷率），与我（当前登录用户）相关的所有问题数；
2.几个趋势图表，所有项目问题趋势，新增问题趋势，所有项目严重问题总数及趋势
3.这个汇总信息的报告导出功能

**Comment by alexqin2018** [comment]
已记录
