### ISSUE TITLE
配置界面点击执行，呈现一种卡死状态，界面显示进度条和字幕一直不会消失

### ISSUE THREAD

**Issue by Shilanla** [alexqin2018/cloud#16]
在配置界面中直接点执行，最后进度条会卡住不动，但实际上已经执行完成
![image](https://user-images.githubusercontent.com/46619063/51155362-33929300-18b2-11e9-86da-338d20ebdb3f.png)

**Comment by Shilanla** [comment]
![image](https://user-images.githubusercontent.com/46619063/51155451-8409f080-18b2-11e9-9f60-8176e2e1be8b.png)

**Comment by alexqin2018** [comment]
单用户多点登录引起，关闭单用户多点登录后即可修复
