### ISSUE TITLE
考虑增加一个快捷向导：用于创建一个demo项目，供用户体验自动化测试。

### ISSUE THREAD

**Issue by chenruibuaa** [alexqin2018/cloud#4]
可以叫“创建演示项目”，所有参数都默认填写（甚至可以简化不显示，更傻瓜），仅让用户选择工具链，DEMO项目的文件来源默认给定，对用户不可见。然后进入自动执行，速度要快。最后用户查看结果。

**Comment by alexqin2018** [comment]
已记录
