### ISSUE TITLE
选择队员的对话框一页一次性显示人名个数下拉框点击无效

### ISSUE THREAD

**Issue by yfyyyfff** [alexqin2018/cloud#7]
![image](https://user-images.githubusercontent.com/9607199/51067720-ac45e500-164f-11e9-9fa1-6c89c3ac96e1.png)

**Comment by yfyyyfff** [comment]
问题2: 添加组员时,选择第一页的5个人,然后换到第二页,再全部选择5个人,确认后只有第二页的人被添加进来

**Comment by alexqin2018** [comment]
1. 已记录
2. 目前所有复选不支持跨页
